spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reserve?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: mysql

  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    generate-ddl: false

  jwt:
    key: ZG9kby1zcHJpbmctYm9vdC1yZXNlcnZhdGlvbi1zZXJ2aWNlLWp3dC1zZWNyZXQta2V5LXN1cGVyLXNlY3JldC15ZXMteWVzCg==

