### signup
POST {{host}}/api/v1/auth/signup
Content-Type: application/json

{
  "name": "lee",
  "email": "test2@gmail.com",
  "password": "kimdodo1234",
  "phoneNumber": "010-1234-1234",
  "role": "USER"
}

### signin
POST {{host}}/api/v1/auth/signin
Content-Type: application/json

{
"email": "test@gmail.com",
"password": "kimdodo1234"
}

> {% //response handler
    client.global.set("token", response.headers.valueOf("Authorization"));
%}