### reserve
POST {{host}}/api/v1/reservation
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "memberKey": "1e2a0015d9e04087957dcf9df24e95a5",
  "storeKey": "4700c057dbab46aaad11b35cbf406fb6",
  "reservationDate": "2023-11-26",
  "reservationTime": "00:30",
  "persons": 2
}

### get reservations for menager
GET {{host}}/api/v1/reservation?storeKey=4700c057dbab46aaad11b35cbf406fb6&reservationDate=2023-11-26&page=0
Authorization: Bearer {{token-mng}}

### confirm reservation
PATCH {{host}}/api/v1/reservation/confirm
Content-Type: application/json
Authorization: Bearer {{token-mng}}

{
  "reservationKey": "96382f913c184d5ebaa73595801a14ee",
  "reservationType": "CONFIRM"
}

### check visit
PATCH {{host}}/api/v1/reservation/visit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "phoneNumber": "010-1234-1234",
  "storeKey": "4700c057dbab46aaad11b35cbf406fb6",
  "reservationDate": "2023-11-26",
  "reservationTime": "00:30"
}

