### reserve
POST {{host}}/api/v1/reservation
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "memberKey": "8e716239b57545f98e444d9be92e3825",
  "storeKey": "b8bea04d945d4f9e8e9a4a46da21501b",
  "reservationDate": "2023-11-26",
  "reservationTime": "00:30",
  "persons": 2
}

### get reservations for menager
GET {{host}}/api/v1/reservation?storeKey=4700c057dbab46aaad11b35cbf406fb6&reservationDate=2023-11-26&page=0
Authorization: Bearer {{token-mng}}

### confirm reservation
PATCH {{host}}/api/v1/reservation/confirm
Content-Type: application/json
Authorization: Bearer {{token-mng}}

{
  "reservationKey": "243fcd5b0503457e9d70d36d04b92cb2",
  "reservationType": "CONFIRM"
}

### check visit
PATCH {{host}}/api/v1/reservation/visit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "phoneNumber": "010-1234-1234",
  "storeKey": "b8bea04d945d4f9e8e9a4a46da21501b",
  "reservationDate": "2023-11-26",
  "reservationTime": "00:30"
}

