### registraton store
POST {{host}}/api/v1/stores
Content-Type: application/json
Authorization: Bearer {{token-mng}}

{
  "memberKey": "91f59504a0d04b6d959a1e2473e0e50d",
  "storeName": "매장 1",
  "description": "매장 1 설명입니다.",
  "phoneNumber": "02-123-1234",
  "address": {
    "address": "서울시 마포구 와우산로24길 13",
    "detailAddr": "AA빌딩",
    "zipcode": "123-1"
  },
  "salesInfo": {
    "operatingStart": "10:00",
    "operatingEnd": "21:00",
    "closedDays": ["수요일", "일요일"]
  }
}

### search store by keyword
GET {{host}}/api/v1/stores/search?keyword=장
Authorization: Bearer {{token}}

### get store information
GET {{host}}/api/v1/stores/1f2bfd69ca2b4698835f14c4ab26383a
Authorization: Bearer {{token}}

### edit store
PATCH {{host}}/api/v1/stores
Content-Type: application/json
Authorization: Bearer {{token-mng}}

{
  "storeKey": "1f2bfd69ca2b4698835f14c4ab26383a",
  "storeName": "그동네 떡볶이",
  "description": "매장 설명입니다.",
  "phoneNumber": "02-123-1234",
  "address": {
    "address": "서울시 마포구 와우산로27길 14",
    "detailAddr": "강강 빌딩",
    "zipcode": "593-6"
  },
  "salesInfo": {
    "operatingStart": "10:00",
    "operatingEnd": "21:00",
    "closedDays": ["일요일"]
  }
}

### delete store
DELETE {{host}}/api/v1/stores/910449774c6c4292b208d65f6ba61bda
Content-Type: application/json
Authorization: Bearer {{token-mng}}

### get store list
GET {{host}}/api/v1/stores?page=0&size=5&sort=name